version: '2'
networks: 
  crm:
volumes: 
  devpeer:
  devpeer-worldstate:
  data-ca:

services: 
  devpeer:
    container_name: devpeer
    extends:
      file: ./base/base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=devpeer
      - CORE_PEER_ADDRESS=devpeer:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=devpeer:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=devpeer:7051
      - CORE_PEER_LOCALMSPID=PeepaltreeMSP

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=database:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
        - /var/run/:/host/var/run/
        - ./cm.shadesix.in/peers/devpeer/msp:/etc/hyperledger/fabric/msp
        - ./cm.shadesix.in/peers/devpeer/tls:/etc/hyperledger/fabric/tls
        - devpeer:/var/hyperledger/production
    ports:
      - 7051:7051
    # extra_hosts: 
      # - orderer: orderer's private IP
    networks: 
      - crm
  
  database:
        container_name: database
        image: hyperledger/fabric-couchdb
        environment:
            - COUCHDB_USER=
            - COUCHDB_PASSWORD=
        volumes:
            - devpeer-worldstate:/opt/couchdb
        networks:
            - crm
        ports: 
          - 5984:5984
        depends_on:
          - devpeer
  
  ca:
        container_name: ca
        extends:
            file: ./base/base.yaml
            service: ca-base
        environment:
            - FABRIC_CA_SERVER_CA_NAME=ca
        volumes:
            - ./cm.shadesix.in/ca:/ca
            - data-ca:/etc/hyperledger/fabric-ca-server
        ports:
            - 7054:7054
        networks:
            - crm
  
