version: '2'
networks: 
  crm:
services: 
  nodeserver:
    container_name: nodeserver
    build: .
    networks: 
      - crm
    ports: 
      - 3000:3000
    extra_hosts: 
      - "orderer:10.0.20.25"
      - "orderer1:10.0.20.195"
      - "devpeer:10.0.20.59"